config/routes.rb
TestApp::Application.routes.draw do
  resources :registration_informations

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
end

app/models/registration_information.rb
class RegistrationInformation < ActiveRecord::Base

  validates_presence_of :name, :email, :password, :phone, :age
  validates_inclusion_of :age, :in => 18..300, :message => "You must be from 18 to 300 years old!"
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Enter corect email address!"
  validates_format_of :phone, :with => /[0-9]{7}/, :message => "Only 7 didgits phone numbers supported!"
  validates_length_of :description, :maximum => 140, :message => "Must be tweetable!"

  attr_accessor :terms_of_service
  validates_acceptance_of :terms_of_service


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/registration_informations_controller.rb
class RegistrationInformationsController < ApplicationController
  # GET /registration_informations
  # GET /registration_informations.xml
  def index
    @registration_informations = RegistrationInformation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @registration_informations }
    end
  end

  # GET /registration_informations/1
  # GET /registration_informations/1.xml
  def show
    @registration_information = RegistrationInformation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @registration_information }
    end
  end

  # GET /registration_informations/new
  # GET /registration_informations/new.xml
  def new
    @registration_information = RegistrationInformation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @registration_information }
    end
  end

  # GET /registration_informations/1/edit
  def edit
    @registration_information = RegistrationInformation.find(params[:id])
  end

  # POST /registration_informations
  # POST /registration_informations.xml
  def create
    @registration_information = RegistrationInformation.new(params[:registration_information])

    respond_to do |format|
      if @registration_information.save
        format.html { redirect_to(@registration_information, :notice => 'Registration information was successfully created.') }
        format.xml  { render :xml => @registration_information, :status => :created, :location => @registration_information }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @registration_information.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /registration_informations/1
  # PUT /registration_informations/1.xml
  def update
    @registration_information = RegistrationInformation.find(params[:id])

    respond_to do |format|
      if @registration_information.update_attributes(params[:registration_information])
        format.html { redirect_to(@registration_information, :notice => 'Registration information was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @registration_information.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_informations/1
  # DELETE /registration_informations/1.xml
  def destroy
    @registration_information = RegistrationInformation.find(params[:id])
    @registration_information.destroy

    respond_to do |format|
      format.html { redirect_to(registration_informations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_informations_helper.rb
module RegistrationInformationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Html 5 forms for rails 3.</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body class="container_12">

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<article class="grid_8">


<h1>Html 5 forms for rails 3.</h1>
<p>
  This is demo for <a href="#">%projectname%</a> project. It allows
  you to generate rich html 5 forms out of
  your <code>ActiveModel</code> classes.
</p>
<p>
  For example you have following model:
</p>
<pre>
  <code>
    class Post < ActiveRecord::Base
      validates_presence_of :title
    end    
  </code>
</pre>
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</article>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/registration_informations/_form.html.erb
<h1>Html 5 forms for rails 3.</h1>
<p>
  This is demo for <a href="#">html5forms</a> project. It allows
  you to generate rich html 5 forms out of
  your <code>ActiveModel</code> classes. They will be validated on client side.
</p>
<p>
  For example you have model that is described by following code:
</p>

<script src="https://gist.github.com/947973.js"> </script>
<p>
  Default ruby <code>form_for</code> helper will generate simple <code>input</code> tags. But if you will add <b>Html5Forms</b> to you gem file it will generate following form:
</p>
  
<section class="grid_4 alpha" >

<%= form_for(@registration_information) do |f| %>
  <% if @registration_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registration_information.errors.count, "error") %> prohibited this registration_information from being saved:</h2>

      <ul>
      <% @registration_information.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="check_box">
    <img src="/images/ast.png" class="" alt="(required)" />
    <%= f.label :terms_of_service %>
    <%= f.check_box :terms_of_service %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</section>
<section class="grid_8">
  <ul id="code_blocks">
    <li><code>&lt;input id="registration_information_name" name="registration_information[name]" required="required" size="30" title="can't be blank" type="text" /&gt;</code></li>
    <li><code>&lt;input id="registration_information_password" name="registration_information[password]" required="required" size="30" title="can't be blank" type="password" /></code></li>
    <li><code>&lt;input id="registration_information_email" name="registration_information[email]" pattern="^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$" required="required" size="30" title="Enter corect email address!" type="email" /></code></li>
    <li><code>&lt;input id="registration_information_age" name="registration_information[age]" pattern="18|19| ... |299|300" required="required" size="30" title="You must be from 18 to 300 years old!" type="text" /></code></li>
    <li><code>&lt;input id="registration_information_phone" name="registration_information[phone]" pattern="[0-9]{7}" required="required" size="30" title="Only 7 didgits phone numbers supported!" type="text" /></code></li>
    <li><code>&ltinput id="registration_information_terms_of_service" name="registration_information[terms_of_service]" required="required" title="must be accepted" type="checkbox" value="1" /></code></li>
    
  </ul>

</section>
<div class="clear"></div>
<br />
<p>For browser that yet do not support html5(hello IE!) you can use <a href="http://flowplayer.org/tools/validator/index.html">http://flowplayer.org/tools/validator/index.html</a>.
</p>

app/views/registration_informations/edit.html.erb
<h1>Editing registration_information</h1>

<%= render 'form' %>

<%= link_to 'Show', @registration_information %> |
<%= link_to 'Back', registration_informations_path %>

app/views/registration_informations/index.html.erb
<h1>Listing registration_informations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Email</th>
    <th>Age</th>
    <th>Phone</th>
    <th>Description</th>
    <th>Anti bot check</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @registration_informations.each do |registration_information| %>
  <tr>
    <td><%= registration_information.name %></td>
    <td><%= registration_information.password %></td>
    <td><%= registration_information.email %></td>
    <td><%= registration_information.age %></td>
    <td><%= registration_information.phone %></td>
    <td><%= registration_information.description %></td>
    <td><%= registration_information.anti_bot_check %></td>
    <td><%= link_to 'Show', registration_information %></td>
    <td><%= link_to 'Edit', edit_registration_information_path(registration_information) %></td>
    <td><%= link_to 'Destroy', registration_information, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Registration information', new_registration_information_path %>

app/views/registration_informations/new.html.erb
<%= render 'form' %>

app/views/registration_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @registration_information.name %>
</p>

<p>
  <b>Password:</b>
  <%= @registration_information.password %>
</p>

<p>
  <b>Email:</b>
  <%= @registration_information.email %>
</p>

<p>
  <b>Age:</b>
  <%= @registration_information.age %>
</p>

<p>
  <b>Phone:</b>
  <%= @registration_information.phone %>
</p>

<p>
  <b>Description:</b>
  <%= @registration_information.description %>
</p>

<p>
  <b>Anti bot check:</b>
  <%= @registration_information.anti_bot_check %>
</p>


<%= link_to 'Edit', edit_registration_information_path(@registration_information) %> |
<%= link_to 'Back', registration_informations_path %>